appName: appName
logLevel: WARN

AWS:
  Region: us-east-1
  Resources:
    EC2:
      Type: "AWS::EC2::Instance"
      Properties:
        ImageId: "ami-0ff8a91507f77f867"
        InstanceType: t2.micro
        KeyName: testkey
        BlockDeviceMappings:
          -
            DeviceName: /dev/sdm
            Ebs:
              VolumeType: io1
              Iops: 200
              DeleteOnTermination: false
              VolumeSize: 20
    Lambda:
        Type: "AWS::Lambda::Function"
        Properties:
          Handler: "index.handler"
          Role:
            Fn::GetAtt:
              - "LambdaExecutionRole"
              - "Arn"
          Runtime: "python3.8"
          Timeout: 25
          TracingConfig:
            Mode: "Active"

routes:
  admin:
    url: /admin
    template: admin.html
    assets:
        templates: /templates
        static: /static
  dashboard:
    url: /dashboard
    template: dashboard.html
    assets:
        templates: /templates
        static: /static
  account:
    url: /account
    template: account.html
    assets:
        templates: /templates
        static: /static

databases:
  cassandra:
    host: example.cassandra.db
    username: user
    password: password
  redshift:
    jdbcURL: jdbc:redshift://<IP>:<PORT>/file?user=username&password=pass
    tempS3Dir: s3://path/to/redshift/temp/dir/
  redis:
    host: hostname
    port: port-number
    auth: authentication
    db: databaseconfig.yaml
